DROP DATABASE IF EXISTS vlabs;
CREATE DATABASE vlabs CHARACTER SET utf8;
DROP USER IF EXISTS 'vlabs'@'localhost';
CREATE USER 'vlabs'@'localhost' IDENTIFIED BY 'vlabs';
GRANT ALL PRIVILEGES ON vlabs.* TO 'vlabs'@'localhost' WITH GRANT OPTION;
FLUSH PRIVILEGES;
