USE vlabs;

-- the password hash is generated by BCrypt Calculator Generator(https://www.dailycred.com/article/bcrypt-calculator)
INSERT INTO users (id, username, password, first_name, last_name, email, phone_number, enabled, last_password_reset_date) VALUES (1, 'admin', '$2a$04$mrdlLQBTR4Hnrl6J2QuOy.C/kt8GoDHPO79qK604nzw.9lyBE7uzO', 'Alexey', 'Maistrenko', 'maskame@gmail.com', '+380661599596', true, NOW());
INSERT INTO users (id, username, password, first_name, last_name, email, phone_number, enabled, last_password_reset_date) VALUES (2, 'user', '$2a$04$mrdlLQBTR4Hnrl6J2QuOy.C/kt8GoDHPO79qK604nzw.9lyBE7uzO', 'Alexey', 'Maistrenko', 'maskame@gmail.com', '+380661599596', true, NOW());

INSERT INTO authority (id, name) VALUES (1, 'ROLE_ADMIN');
INSERT INTO authority (id, name) VALUES (2, 'ROLE_USER');
INSERT INTO authority (id, name) VALUES (3, 'ROLE_MANAGER');

INSERT INTO user_authority (user_id, authority_id) VALUES (1, 1);
INSERT INTO user_authority (user_id, authority_id) VALUES (1, 2);
INSERT INTO user_authority (user_id, authority_id) VALUES (2, 2);
